import { expect, openApp, test } from './fixtures'

test('recetas: pegar el texto, raciones que escalan y modo cocina con temporizador', async ({ page }) => {
  await openApp(page, '/menu')
  await page.getByRole('button', { name: /^Recetas/ }).click()
  await page.getByRole('button', { name: 'Receta', exact: true }).click()
  const box = page.getByLabel('Enlace o texto de la receta')
  // Un enlace sin cuenta: lo explica y propone pegar el texto
  await box.fill('https://www.ejemplo.es/receta-gazpacho')
  await page.getByRole('button', { name: 'Traer de la web' }).click()
  await expect(page.getByRole('alert')).toContainText('hace falta iniciar sesión')
  await box.fill('Gazpacho\nPara 4 personas\n\nIngredientes:\n- 1 kg de tomates\n- 1 pepino\n- Sal\n\nPreparación:\n1. Trocea todo.\n2. Tritura y enfría 20 minutos.')
  await page.getByRole('button', { name: 'Leer el texto' }).click()
  await expect(page.getByLabel('Nombre')).toHaveValue('Gazpacho')
  await page.getByRole('button', { name: 'Guardar' }).click()

  await page.locator('#main button', { hasText: 'Gazpacho' }).click()
  const sheet = page.getByRole('dialog')
  await expect(sheet).toContainText('4 personas')
  await expect(sheet).toContainText('1 kg de tomates')
  await sheet.getByRole('button', { name: 'Una persona más' }).click()
  await sheet.getByRole('button', { name: 'Una persona más' }).click()
  await expect(sheet).toContainText('1,5 kg de tomates')
  await expect(sheet).toContainText('1½ pepino')

  await sheet.getByRole('button', { name: 'Cocinar' }).click()
  const cook = page.getByRole('dialog', { name: 'Cocinar: Gazpacho' })
  await expect(cook).toContainText('Trocea todo.')
  await cook.getByRole('button', { name: 'Siguiente' }).click()
  await expect(cook).toContainText('Tritura y enfría 20 minutos.')
  await cook.getByRole('button', { name: '20 min' }).click()
  await expect(cook.getByRole('timer', { name: 'Temporizador de 20 min' })).toBeVisible()
  await cook.getByRole('button', { name: 'Terminado' }).click()
  await expect(cook).toHaveCount(0)
})

test('compra: varias listas, precios y total estimado', async ({ page }) => {
  await openApp(page, '/shopping')
  const input = page.getByLabel(/^Añadir a la lista/)
  await input.fill('leche 1,20 €, pan 0,80 €')
  await input.press('Enter')
  await expect(page.locator('#main')).toContainText('Unos 2,00 €')

  await page.getByRole('button', { name: 'Nueva lista' }).click()
  await page.getByLabel('Nombre de la nueva lista').fill('Farmacia')
  await page.keyboard.press('Enter')
  await expect(page.getByRole('button', { name: /^Farmacia/ })).toHaveAttribute('aria-pressed', 'true')
  await input.fill('ibuprofeno')
  await input.press('Enter')
  await expect(page.getByRole('checkbox', { name: 'Ibuprofeno al carro' })).toBeVisible()
  await expect(page.getByRole('checkbox', { name: 'Leche al carro' })).toHaveCount(0)
  await page.getByRole('button', { name: 'Poner precio a Ibuprofeno' }).click()
  await page.getByLabel('Precio de Ibuprofeno').fill('3,5')
  await page.keyboard.press('Enter')
  await expect(page.locator('#main')).toContainText('Unos 3,50 €')

  // La principal sigue con lo suyo
  await page.getByRole('button', { name: /^Súper/ }).click()
  await expect(page.getByRole('checkbox', { name: 'Leche al carro' })).toBeVisible()
  await expect(page.getByRole('checkbox', { name: 'Ibuprofeno al carro' })).toHaveCount(0)
})

test('cosas: garantía de 3 años y agrupadas por estancia', async ({ page }) => {
  await openApp(page, '/things')
  await page.getByRole('button', { name: '¿Dónde está el pasaporte?' }).click()
  await page.getByPlaceholder(/Pasaporte/).fill('Lavadora')
  await page.getByLabel('Estancia').fill('Cocina')
  await page.getByLabel('Comprado el').fill('2026-03-01')
  await page.getByLabel('Precio').fill('499')
  await page.getByRole('button', { name: '3 años desde la compra' }).click()
  await expect(page.getByLabel('Garantía hasta')).toHaveValue('2029-03-01')
  await page.getByRole('dialog').getByRole('button', { name: 'Apuntar' }).click()
  await expect(page.locator('#main')).toContainText('Lo apuntado vale unos 499 €')
  await expect(page.locator('#main')).toContainText('Garantía hasta')
  await page.getByRole('button', { name: 'Por estancia' }).click()
  await expect(page.getByRole('heading', { name: 'Cocina' })).toBeVisible()
})

test('limpieza por estancias: lo típico y la barra de suciedad', async ({ page }) => {
  await openApp(page, '/trackers')
  await page.getByRole('button', { name: 'Cambiar las sábanas' }).click()
  await page.getByRole('button', { name: 'Por estancia' }).click()
  await page.getByRole('button', { name: 'Lo típico de baño' }).click()
  await expect(page.getByRole('heading', { name: 'Baño' })).toBeVisible()
  // Nunca hecho: toca
  await expect(page.getByRole('img', { name: 'Limpiar el baño: toca' })).toBeVisible()
  await page.getByRole('button', { name: 'Limpiar el baño: lo he hecho hoy' }).click()
  await expect(page.getByRole('img', { name: 'Limpiar el baño: limpio' })).toBeVisible()
})
